name: 'Deploy to Kubernetes'

on:
  push:
    branches:
      - 'main'

jobs:
  update-deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Decode and set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Run kubectl get sbc
        run: |
          kubectl get sbc       
