name: 'Deploy to Kubernetes'

on:
  push:
    branches:
      - 'main'

jobs:
  update-deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Decode and set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
          kubectl version --client

      - name: gke console verify
        run: sudo apt-get install apt-transport-https ca-certificates gnupg curl

      - name: Importa public key Google cloud
        run : curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      
      - name: Add Uri GCP
        run: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

      - name: Install Gcloud CLI
        run: sudo apt-get update && sudo apt-get install google-cloud-cli
    
      - name: Init GCloud
        run: gcloud init
      # - name: Add Google Cloud SDK repository
      #   run: |
      #     echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      #     sudo apt-get install -y apt-transport-https ca-certificates
      #     sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
      - name: gke console verify
        run: |
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
          gke-gcloud-auth-plugin --version
        # gcloud container clusters get-credentials portfolio-sbx --region=us-central1

      - name: Run kubectl get sbc
        run: |
          kubectl get sbc       
